---
common:
  debug: yes
  version: "development"

sentry:
  dsn: "https://ae8a3840b7754a1d93f704b3e8157e7e@o1117873.ingest.sentry.io/6464231"
  environment: "development"

solr:
  server: http://localhost:8983/solr
  indexing_core: muscatplus_indexing
  live_core: muscatplus_live

indexing:
  extended_incipits: yes

mysql:
  server: localhost
  username: muscat
  password: muscat
  database: muscat_development
  resultsize: 1000

postgres:
  server: localhost
  username: "ahankins"
  password: ""
  database: "diamm_data_server"
  resultsize: 1000