---
solr:
  server: http://localhost:8983/solr
  indexing_core: muscatplus_indexing
  live_core: muscatplus_live

mysql:
  server: localhost
  username: muscat
  password: muscat
  database: muscat_development
  resultsize: 1000