version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: "[%(asctime)s] [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
  colored:
    (): color_formatter.ColorFormatter
    format: "[%(asctime)s] [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
    use_colors: true
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  consoledebug:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  file:
    class: logging.handlers.WatchedFileHandler
    level: WARNING
    formatter: simple
    filename: ./logs/indexer.log
loggers:
  muscat_indexer:
    level: INFO
    handlers: [console, file]
    propagate: no
  authority_link_checker:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: NOTSET
