[tool.poetry]
name = "muscatplus_indexer"
version = "0.1.0"
description = ""
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]

[tool.poetry.dependencies]
python = "^3.9"
dbutils = "^1.3"
pymarc = "^4.0.0"
mysqlclient = "^2.0.1"
pyyaml = "^5.3.1"
uvloop = "^0.14.0"
ujson = "^4.0.2"
edtf = {git = "https://github.com/rism-digital/python-edtf.git", rev = "performance-enhancements"}
python-simhash = {git = "https://github.com/scrapinghub/python-simhash"}
verovio = {git = "https://github.com/rism-digital/verovio.git", rev = "develop-features"}
httpx = "^0.18.2"

[tool.poetry.dev-dependencies]
ipython = "^7.18.1"

[[tool.poetry.source]]
name="testpypi"
url="https://test.pypi.org/simple/"
secondary=true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
