[tool.poetry]
name = "muscatplus_indexer"
version = "v1.0.3"
description = ""
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]

[tool.poetry.dependencies]
python = "^3.9"
dbutils = "^3.0"
pymarc = "^4.0.0"
mysqlclient = "^2.0.1"
pyyaml = "^6.0.0"
uvloop = "^0.16.0"
ujson = "^5.0.0"
edtf = {git = "https://github.com/rism-digital/python-edtf.git", rev = "performance-enhancements"}
httpx = "^0.23.0"
verovio = { version = "^3.11.0.dev85", allow-prereleases = true }
sentry-sdk = "^1.5.12"

[tool.poetry.dev-dependencies]
ipython = "^8.0.0"

[[tool.poetry.source]]
name="testpypi"
url="https://test.pypi.org/simple/"
secondary=true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
